add 2023 tax bills
ccao-data/ptaxsim pull request #41
Opened 2024-07-11 17:57 UTC by erhla

2024-07-11 17:57 UTC, erhla commented
Oops. Here's the 2023 tax bills to add to your branch.

2024-07-11 20:55 UTC, dfsnow reviewed
@erhla Can you fix the linting errors on `sample_tax_bills_detail.R`?

2024-07-22 18:09 UTC, dfsnow commented
@erhla There's also the `data-raw/sample_tax_bills/sample_tax_bills_summary.csv` which needs to be updated manually (by manually looking at the exemption details on each bill). Lmk if you wanna do it, otherwise we can merge this and I'll grab it later.

2024-07-23 18:08 UTC, dfsnow requested changes
@erhla

2024-07-23 18:08 UTC, dfsnow commented on data-raw/sample_tax_bills/sample_tax_bills_summary.R
> +  write_csv(sum_path)
**issue (blocking):** I get the intent but let's not add this programmatically. It's fine if you wanna use it to help jumpstart the manual work on each bill though.

Also, somehow it's mangling the CSV, see below.

2024-07-23 18:08 UTC, dfsnow commented on data-raw/sample_tax_bills/sample_tax_bills_summary.csv
**issue (blocking):** Looks like some of the 0000 PINs get mangled and converted to scientific notation here. No bueno.

2024-08-05 17:19 UTC, merged